/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.User;

/**
 *
 * @author phuongdt
 */
public class SelectStatFuncFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form SelectStatFuncFrm
     */
    private User user;
    public SelectStatFuncFrm(User u) {
        initComponents();
        this.user = u;
        this.setLocationRelativeTo(null);
        btnBackManagerHomeFrm.addActionListener(this);
        btnCsStatByTotalDebtFrm.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackManagerHomeFrm = new javax.swing.JButton();
        btnCsStatByTotalDebtFrm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(884, 600));

        jPanel1.setBackground(new java.awt.Color(224, 246, 230));
        jPanel1.setPreferredSize(new java.awt.Dimension(884, 600));

        btnBackManagerHomeFrm.setBackground(new java.awt.Color(102, 204, 255));
        btnBackManagerHomeFrm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBackManagerHomeFrm.setText("Quay lại");
        btnBackManagerHomeFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackManagerHomeFrmActionPerformed(evt);
            }
        });

        btnCsStatByTotalDebtFrm.setBackground(new java.awt.Color(153, 234, 160));
        btnCsStatByTotalDebtFrm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCsStatByTotalDebtFrm.setText("Thống kê khách hàng theo dư nợ");
        btnCsStatByTotalDebtFrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCsStatByTotalDebtFrmActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(224, 246, 230));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XEM BÁO CÁO THỐNG KÊ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logoevnngangfull (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackManagerHomeFrm)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnCsStatByTotalDebtFrm)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnBackManagerHomeFrm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(btnCsStatByTotalDebtFrm)
                .addGap(203, 203, 203))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackManagerHomeFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackManagerHomeFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackManagerHomeFrmActionPerformed

    private void btnCsStatByTotalDebtFrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsStatByTotalDebtFrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCsStatByTotalDebtFrmActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackManagerHomeFrm;
    private javax.swing.JButton btnCsStatByTotalDebtFrm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == btnBackManagerHomeFrm) {
            this.dispose();
            (new ManagerHomeFrm(user)).setVisible(true);
        } else {
            this.dispose();
            (new CsStatByTotalDebtFrm(user)).setVisible(true);
        }
    }
}
